var scores;
var names;
scores = [ 3, 1, 8, 2];
names = [ "Kandra", "Dax", "Blinky" ];
console.log(scores);
console.log(names);
scores.push(5);
names.push("Zara");
var akaScores;
akaScores = scores;
console.log(akaScores);